apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetesjexxatemplate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetesjexxatemplate
  template:
    metadata:
      labels:
        app: kubernetesjexxatemplate
    spec:
      containers:
        - name: kubernetesjexxatemplate
          image: ghcr.io/nicosaia/kubernetesjexxatemplate:latest
          ports:
            - containerPort: 7500
          env:
            - name: ACTIVEMQ_SERVICE_HOST
              value: activemq-postgres-service
            - name: POSTGRES_SERVICE_HOST
              value: activemq-postgres-service