apiVersion: v1
kind: Service
metadata:
  name: activemq-postgres-service
spec:
  selector:
    app: activemq-postgres
  ports:
    - name: activemq
      port: 61616
      targetPort: 61616
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: jexxatemplate
      port: 7500
      targetPort: 7500
